name: Deploy Staging

on:
  push:
    branches:
      - master

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: deploy serverless
        env: # Or as an environment variable
          GITHUB_ACCESS_TOKEN_STAGING: ${{ secrets.GH_ACCESS_TOKEN_STAGING }}
          GITHUB_ACCESS_TOKEN_PRODUCTION: ${{ secrets.GH_ACCESS_TOKEN_PRODUCTION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npm i
          npm run deploy -- --stage staging
